export default [
    "Change your thoughts and you change your world",
    "Life is 10% what happens to us and 90% how we react to it",
    "The only limit to our realization of tomorrow is our doubts of today",
    "What we achieve inwardly will change outer reality",
    "Act as if what you do makes a difference. It does",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "Your present circumstances don't determine where you can go; they merely determine where you start",
    "Keep your face always toward the sunshine, and shadows will fall behind you",
    "The only way to achieve the impossible is to believe it is possible",
    "The future belongs to those who believe in the beauty of their dreams",
    "Believe you can and you're halfway there",
    "It is never too late to be what you might have been",
    "The purpose of life is to believe, to hope, and to strive",
    "With the new day comes new strength and new thoughts",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us",
    "Do not wait to strike till the iron is hot; but make it hot by striking",
    "Your life does not get better by chance, it gets better by change",
    "It always seems impossible until it is done",
    "The best way to predict the future is to create it",
    "To accomplish great things, we must not only act, but also dream; not only plan, but also believe",
    "Perseverance is not a long race; it is many short races one after the other",
    "Happiness is not something ready-made. It comes from your own actions",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "Don't watch the clock; do what it does. Keep going",
    "Dream big and dare to fail",
    "Your time is limited, don't waste it living someone else's life",
    "Strive not to be a success, but rather to be of value",
    "You must be the change you wish to see in the world",
    "Life isn't about getting and having, it's about giving and being",
    "The only person you are destined to become is the person you decide to be",
    "Whatever you are, be a good one",
    "The best revenge is massive success",
    "Do what you can, with what you have, where you are",
    "Act as if what you do makes a difference. It does",
    "The best way out is always through",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "Success is not the key to happiness. Happiness is the key to success",
    "Your time is limited, so don't waste it living someone else's life",
    "The only way to do great work is to love what you do",
    "The best time to plant a tree was 20 years ago. The second best time is now",
    "The journey of a thousand miles begins with one step",
    "Success is not in what you have, but who you are",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment",
    "Don't be afraid to give up the good to go for the great",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
    "Success is not final, failure is not fatal: It is the courage to continue that counts",
    "It is better to fail in originality than to succeed in imitation",
    "Do not wait to strike till the iron is hot; but make it hot by striking",
    "Success usually comes to those who are too busy to be looking for it",
    "Don't be afraid to give up the good to go for the great",
    "Success is not the key to happiness. Happiness is the key to success",
    "The way to get started is to quit talking and begin doing",
    "Don't let yesterday take up too much of today",
    "Don't judge each day by the harvest you reap but by the seeds that you plant",
    "To handle yourself, use your head; to handle others, use your heart",
    "Keep your eyes on the stars, and your feet on the ground",
    "The future depends on what you do today",
    "The purpose of our lives is to be happy",
    "Don't let the fear of losing be greater than the excitement of winning",
    "The only person you should try to be better than is the person you were yesterday",
    "Happiness is not something ready-made. It comes from your own actions",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "Life is 10% what happens to us and 90% how we react to it",
    "Believe you can and you're halfway there",
    "It always seems impossible until it is done",
    "The only way to achieve the impossible is to believe it is possible",
    "Life is what happens when you're busy making other plans",
    "Strive not to be a success, but rather to be of value",
    "Your time is limited, don't waste it living someone else's life",
    "Don't judge each day by the harvest you reap but by the seeds that you plant",
    "The only limit to our realization of tomorrow is our doubts of today",
    "With the new day comes new strength and new thoughts",
    "It does not matter how slowly you go as long as you do not stop",
    "The future belongs to those who believe in the beauty of their dreams",
    "You must be the change you wish to see in the world",
    "The best way to predict your future is to create it",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "Success is not final, failure is not fatal: It is the courage to continue that counts",
    "The best way to find yourself is to lose yourself in the service of others",
    "It is never too late to be what you might have been",
    "Dream big and dare to fail",
    "Don't watch the clock; do what it does. Keep going",
    "The only person you are destined to become is the person you decide to be",
    "What you get by achieving your goals is not as important as what you become by achieving your goals",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "Life isn't about getting and having, it's about giving and being",
    "You miss 100% of the shots you don't take",
    "The only way to do great work is to love what you do",
    "Don't be afraid to give up the good to go for the great",
    "Believe you can and you're halfway there",
    "The best time to plant a tree was 20 years ago. The second best time is now",
    "The only limit to our realization of tomorrow is our doubts of today",
    "The best way out is always through",
    "Success is not in what you have, but who you are",
    "Do not wait to strike till the iron is hot; but make it hot by striking",
    "The only person you are destined to become is the person you decide to be",
    "Keep your eyes on the stars, and your feet on the ground",
    "Don't let the fear of losing be greater than the excitement of winning",
    "Success usually comes to those who are too busy to be looking for it",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "The best revenge is massive success",
    "Success is not the key to happiness. Happiness is the key to success",
    "The journey of a thousand miles begins with one step",
    "It is better to fail in originality than to succeed in imitation",
    "Your life does not get better by chance, it gets better by change",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment",
    "The future belongs to those who believe in the beauty of their dreams",
    "Don't be afraid to give up the good to go for the great",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people",
    "Do what you can, with what you have, where you are",
    "Don't let yesterday take up too much of today",
    "Success is not final, failure is not fatal: It is the courage to continue that counts",
    "The purpose of our lives is to be happy",
    "Don't judge each day by the harvest you reap but by the seeds that you plant",
    "It does not matter how slowly you go as long as you do not stop",
    "The best way to find yourself is to lose yourself in the service of others",
    "Success is not in what you have, but who you are",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
    "Don't let the fear of losing be greater than the excitement of winning",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "Success is not final, failure is not fatal: It is the courage to continue that counts",
    "The best way to predict your future is to create it",
    "It always seems impossible until it is done",
    "Your time is limited, so don't waste it living someone else's life",
    "The only way to achieve the impossible is to believe it is possible",
    "Dream big and dare to fail",
    "The future depends on what you do today",
    "Don't watch the clock; do what it does. Keep going",
    "Success is not how high you have climbed, but how you make a positive difference to the world",
    "It is never too late to be what you might have been",
];